#!/usr/bin/env python3
"""Writes src/data/exerciseMedia.ts and src/data/exerciseLibrary.ts from assets/exercise-media.

Run after scripts/build_exercise_media.sh. Metro needs a literal require() per file, so the
media index is generated rather than built at runtime.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), '..')
MEDIA = os.path.join(ROOT, 'assets', 'exercise-media')

slugs = sorted(
    f[:-4]
    for f in os.listdir(os.path.join(MEDIA, 'dark'))
    if f.endswith('.mp4')
    and all(os.path.exists(os.path.join(MEDIA, d, f[:-4] + '.jpg')) for d in ('poster', 'thumb', 'hero'))
)

# ---------- media index ----------
out = [
    '// Generated by scripts/gen_exercise_index.py. Do not edit by hand.',
    '// video: 1440px x-ray loop · poster: dark still (first frame) · thumb: light square · hero: dark portrait',
    'export interface ExerciseMedia { video: number; poster: number; thumb: number; hero: number }',
    '',
    'const MEDIA: Record<string, ExerciseMedia> = {',
]
for s in slugs:
    out += [
        f"  '{s}': {{",
        f"    video: require('../../assets/exercise-media/dark/{s}.mp4'),",
        f"    poster: require('../../assets/exercise-media/poster/{s}.jpg'),",
        f"    thumb: require('../../assets/exercise-media/thumb/{s}.jpg'),",
        f"    hero: require('../../assets/exercise-media/hero/{s}.jpg'),",
        '  },',
    ]
out += [
    '};',
    '',
    'export function getExerciseMedia(key?: string): ExerciseMedia | undefined {',
    '  return key ? MEDIA[key] : undefined;',
    '}',
    '',
]
open(os.path.join(ROOT, 'src', 'data', 'exerciseMedia.ts'), 'w').write('\n'.join(out))

# ---------- browsable library (from MoveKit metadata) ----------
import json

META = json.load(open(os.path.join(ROOT, 'scripts', 'data', 'movekit-metadata.json')))
have = set(slugs)

EQUIP_GROUP = {
    'Barbell': 'barbell', 'Dumbbell': 'dumbbell', 'Kettlebell': 'kettlebell', 'Cable Machine': 'cable',
    'Machine': 'machine', 'Band': 'band', 'Bodyweight': 'bodyweight', 'Bench': 'bodyweight',
    'Stability Ball': 'bodyweight', 'Weight Plate': 'other', 'Sled': 'other', 'Battle Ropes': 'other',
    'Wrist Roller': 'other', 'Bicycle': 'cardio',
}


def group(m):
    pattern = set(m['movementPattern'])
    if 'swim' in m['slug']:
        return 'swim'
    if pattern & {'Mobility', 'Stretch'}:
        return 'mobility'
    if 'Cardio' in pattern:
        return 'cardio'
    for e in m['equipment']:
        if e in EQUIP_GROUP and e != 'Bodyweight':
            return EQUIP_GROUP[e]
    return 'bodyweight'


items = []
for m in META:
    if m['slug'] not in have:
        continue
    items.append({
        'key': m['slug'],
        'name': m['name'],
        'group': group(m),
        'equipment': m['equipment'],
        'primary': m['primaryMuscles'],
        'secondary': m['secondaryMuscles'],
        'pattern': m['movementPattern'],
        'difficulty': m['difficulty'],
        'summary': m['shortDescription'],
        'instructions': m['instructions'],
        'mistakes': m['commonMistakes'],
        'benefits': m['benefits'],
        'tags': m['tags'] + m['aliases'],
    })
items.sort(key=lambda i: i['name'].lower())
json.dump(items, open(os.path.join(ROOT, 'src', 'data', 'exerciseLibrary.json'), 'w'), ensure_ascii=False, separators=(',', ':'))

lib = """// Generated by scripts/gen_exercise_index.py from scripts/data/movekit-metadata.json. Do not edit by hand.
import data from './exerciseLibrary.json';

export type LibraryGroup = 'barbell' | 'dumbbell' | 'kettlebell' | 'cable' | 'machine' | 'band' | 'bodyweight' | 'other' | 'cardio' | 'swim' | 'mobility';

export interface LibraryItem {
  key: string;
  name: string;
  group: LibraryGroup;
  equipment: string[];
  primary: string[];
  secondary: string[];
  pattern: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  summary: string;
  instructions: string[];
  mistakes: string[];
  benefits: string[];
  tags: string[];
}

export const EXERCISE_LIBRARY = data as LibraryItem[];

const BY_KEY = new Map(EXERCISE_LIBRARY.map((i) => [i.key, i]));

export function getLibraryItem(key: string): LibraryItem | undefined {
  return BY_KEY.get(key);
}

/** Library muscle names mapped to the app's muscle vocabulary (body map, distribution). */
const MUSCLE: Record<string, string> = {
  Glutes: 'glutes', Quadriceps: 'quads', Back: 'back', Shoulders: 'shoulders', Core: 'core', Chest: 'chest',
  Hamstrings: 'hamstrings', Trapezius: 'traps', Biceps: 'biceps', Triceps: 'triceps', Calves: 'calves',
  Forearms: 'forearms', 'Lower Back': 'lower_back', Adductors: 'adductors', Neck: 'traps', Tibialis: 'calves',
};

export function appMuscles(item: LibraryItem): string[] {
  return Array.from(new Set([...item.primary, ...item.secondary].map((m) => MUSCLE[m]).filter(Boolean)));
}
"""
open(os.path.join(ROOT, 'src', 'data', 'exerciseLibrary.ts'), 'w').write(lib)
print(f'{len(slugs)} media, {len(items)} library items')
