// Generated by scripts/gen_exercise_index.py from scripts/data/movekit-metadata.json. Do not edit by hand.
import data from './exerciseLibrary.json';

export type LibraryGroup = 'barbell' | 'dumbbell' | 'kettlebell' | 'cable' | 'machine' | 'band' | 'bodyweight' | 'other' | 'cardio' | 'swim' | 'mobility';

export interface LibraryItem {
  key: string;
  name: string;
  group: LibraryGroup;
  equipment: string[];
  primary: string[];
  secondary: string[];
  pattern: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  summary: string;
  instructions: string[];
  mistakes: string[];
  benefits: string[];
  tags: string[];
}

export const EXERCISE_LIBRARY = data as LibraryItem[];

const BY_KEY = new Map(EXERCISE_LIBRARY.map((i) => [i.key, i]));

export function getLibraryItem(key: string): LibraryItem | undefined {
  return BY_KEY.get(key);
}

/** Library muscle names mapped to the app's muscle vocabulary (body map, distribution). */
const MUSCLE: Record<string, string> = {
  Glutes: 'glutes', Quadriceps: 'quads', Back: 'back', Shoulders: 'shoulders', Core: 'core', Chest: 'chest',
  Hamstrings: 'hamstrings', Trapezius: 'traps', Biceps: 'biceps', Triceps: 'triceps', Calves: 'calves',
  Forearms: 'forearms', 'Lower Back': 'lower_back', Adductors: 'adductors', Neck: 'traps', Tibialis: 'calves',
};

export function appMuscles(item: LibraryItem): string[] {
  return Array.from(new Set([...item.primary, ...item.secondary].map((m) => MUSCLE[m]).filter(Boolean)));
}
