// Plan library generated by ~/Desktop/gruntz-plans (build.py). Do not edit the JSON by hand.
// Units: rest_seconds / duration_seconds in seconds, distance_meters in meters, *_minutes in minutes.
import { getLibraryItem, LibraryItem } from './exerciseLibrary';

export type PlanLevel = 'beginner' | 'intermediate' | 'advanced';
export type PlanEquipmentAccess = 'none' | 'minimal' | 'gym';
export type PlanMeasure = 'reps' | 'time' | 'distance' | 'amrap' | 'failure';
export type VideoMatch = 'exact' | 'substitute' | 'similar' | 'none';

/** One exercise as it appears across all plans, with its matched library video. */
export interface PlanExerciseInfo {
  name: string;
  primary_muscles: string[];
  secondary_muscles: string[];
  equipment: string[];
  movement_pattern: string;
  /** Library slug (same key as exerciseLibrary / exerciseMedia), or null when no video is close enough. */
  video_key: string | null;
  /** exact = same exercise; substitute = different exercise, same main muscles and movement;
   *  similar = closest available clip for the same main muscles (show as "closest video"); none = no clip. */
  video_match: VideoMatch;
  match_score: number | null;
  /** Other acceptable videos, best first. */
  alternative_video_keys: string[];
}

/** One prescribed exercise inside a plan day. Optional fields are omitted when not applicable. */
export interface PlanExerciseSlot {
  order: number;
  exercise_id: string;
  /** Clean display name, same as PLAN_EXERCISES[exercise_id].name. */
  name: string;
  video_key: string | null;
  measure: PlanMeasure;
  sets: number;
  /** Average of the prescribed range (8-12 -> 10). Present for measure 'reps'. */
  reps?: number;
  reps_min?: number;
  reps_max?: number;
  /** Per-set reps for pyramids, e.g. [12, 10, 8]. */
  rep_scheme?: number[];
  per_side?: boolean;
  duration_seconds?: number;
  distance_meters?: number;
  rest_seconds: number;
  /** Exercises sharing a letter are done back to back. */
  superset_group?: string;
  warmup_sets?: number;
  notes?: string;
  progression?: string;
  /** Fields filled with app defaults because the source plan left them blank. */
  defaults_applied?: string[];
}

export interface PlanDay {
  id: string;
  index: number;
  week: number | null;
  /** "Day 1", or "Week 2 · Day 1" for plans that change week to week. */
  label: string;
  /** What the day trains, e.g. "Legs", "Chest & Triceps", "Full Body". */
  title: string;
  estimated_minutes: number;
  exercises: PlanExerciseSlot[];
}

export interface WorkoutPlanSummary {
  main_goal: string | null;
  workout_type: string | null;
  level: PlanLevel | null;
  duration_weeks: number | null;
  days_per_week: number | null;
  session_minutes: number | null;
  session_minutes_min: number | null;
  session_minutes_max: number | null;
  equipment: string[];
  target_gender: string | null;
  supplements: string[];
}

/** Fields lined up with onboarding answers (UserProfile). */
export interface WorkoutPlanMatch {
  /** Same labels as the onboarding goal chips, plus 'Build Muscle'. */
  goals: string[];
  fitness_level: PlanLevel;
  days_per_week: number | null;
  session_minutes: number | null;
  equipment_access: PlanEquipmentAccess;
}

export interface WorkoutPlan {
  id: string;
  /** 'program' = multi-day plan to follow; 'single_workout' = one standalone session. */
  kind: 'program' | 'single_workout';
  title: string;
  description: string | null;
  categories: string[];
  summary: WorkoutPlanSummary;
  match: WorkoutPlanMatch;
  stats: {
    days: number;
    exercises: number;
    exercises_with_video: number;
    exact_videos: number;
    substituted_videos: number;
    similar_videos: number;
    video_coverage: number;
  };
  days: PlanDay[];
}

export interface PlanCategory {
  id: string;
  name: string;
  plan_ids: string[];
}

interface WorkoutPlansFile {
  version: number;
  generated_at: string;
  categories: PlanCategory[];
  exercises: Record<string, PlanExerciseInfo>;
  plans: WorkoutPlan[];
}

/**
 * The plan file is ~4 MB, so it is parsed on first use rather than at import: nothing on the
 * startup path (stores, Train tab) should pay for it before the user opens a plan.
 */
let FILE: WorkoutPlansFile | null = null;
function file(): WorkoutPlansFile {
  if (!FILE) FILE = require('./workoutPlans.json') as unknown as WorkoutPlansFile;
  return FILE;
}

/** How many plans ship with the app — a plain number, so counters don't load the file. */
export const PLAN_COUNT = 528;

export function allPlans(): WorkoutPlan[] {
  return file().plans;
}

export function planCategories(): PlanCategory[] {
  return file().categories.filter((c) => c.plan_ids.length > 0);
}

export function planExercises(): Record<string, PlanExerciseInfo> {
  return file().exercises;
}

let BY_ID: Map<string, WorkoutPlan> | null = null;
function byId() {
  if (!BY_ID) BY_ID = new Map(allPlans().map((p) => [p.id, p]));
  return BY_ID;
}

export function getWorkoutPlan(id: string): WorkoutPlan | undefined {
  return byId().get(id);
}

export function getPlansInCategory(categoryId: string): WorkoutPlan[] {
  const cat = planCategories().find((c) => c.id === categoryId);
  return cat ? cat.plan_ids.map((id) => byId().get(id)).filter((p): p is WorkoutPlan => !!p) : [];
}

export function getPlanExercise(slot: PlanExerciseSlot): PlanExerciseInfo | undefined {
  return planExercises()[slot.exercise_id];
}

/** Library clip for a slot (poster/thumb/video via getExerciseMedia(slot.video_key)). */
export function getSlotLibraryItem(slot: PlanExerciseSlot): LibraryItem | undefined {
  return slot.video_key ? getLibraryItem(slot.video_key) : undefined;
}
